---
layout: page
title: "XAI"
subtitle: "`archivist` 모형 객체"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "설명가능한 AI", "XAI", "Explainable AI", "모형 객체", "archivist"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_xai.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 데이터와 모형 가져오기 [@archivist] {#import-models-datasets}

## 데이터 가져오기 {#import-models-datasets-titanic}

타이타닉 데이터셋은 기계학습 모형 구축에 있어 무척이나 중요하다. [`archivist`](https://www.jstatsoft.org/article/view/v082i11)를 통해 R 객체와 데이터를 저장하고 필요에 따라 공유하는 것이 가능하다. 먼저 타이타닉 데이터셋과 쟈니(Jonny)가 타이타닉호에 승선했을 때 생존 확률을 알아보자. 참고로 쟈니는 8살이고 Southampton에서 탑승했고, 72 파운드를 지불했으며 부모없이 1등석에 탑승한 정보가 있다. `henry`는 47로, 1등석에 탑승했으며, 혼자 여행중이였으며 25 파운드를 배삭으로 지불했고, Cherbourg 에서 탑승했다.

```{r import-models-datasets, error=TRUE}
# devtools::install_github("pbiecek/archivist")
library(archivist)

titanic  <- archivist::aread("pbiecek/models/27e5c")
johnny_d <- archivist::aread("pbiecek/models/e3596")
henry    <- archivist::aread("pbiecek/models/a6538")
```

```{r load-dataset, error=TRUE}
titanic %>% 
  reactable::reactable()
```


```{r predictive-model, error=TRUE}
titanic_lmr <- archivist::aread("pbiecek/models/58b24")
titanic_rf  <- archivist::aread("pbiecek/models/4e0fc")
titanic_gbm <- archivist::aread("pbiecek/models/b7078")
titanic_svm <- archivist::aread("pbiecek/models/9c27f")
```




